name: Bug Report
description: Report a bug or a problem you've found
title: '[BUG] '
labels: ['type:bug']
body:
    - type: textarea
      id: description
      attributes:
          label: Description
          description: Description of what the bug is.
      validations:
          required: true
    - type: textarea
      id: environment
      attributes:
          label: Environment
          description: Indicate the running environment, e.g. operating system, software version.
      validations:
          required: true
    - type: textarea
      id: reproduction-steps
      attributes:
          label: Reproduction steps
          description: Steps to reproduce the behavior.
      validations:
          required: true
    - type: textarea
      id: expected-behavior
      attributes:
          label: Expected behavior
          description: Description of what you expected to happen.
    - type: input
      id: relevant-logs
      attributes:
          label: Relevant logs
          description: Please post logs using pastebin.com or GitHub Gist, and paste the link here.
          placeholder: e.g. https://pastebin.com/rP253aGf
