name: Metrics
on:
    schedule: # Schedule updates (each 6 hours)
        - cron: '5 */6 * * *'
    workflow_dispatch:
jobs:
    github-metrics:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Metrics
              uses: lowlighter/metrics@latest
              with:
                  token: ${{ secrets.METRICS_TOKEN }}
                  user: auioc
                  template: classic
                  base: header, activity, community, repositories
                  config_timezone: Asia/Shanghai
                  output_action: none
                  # Languages
                  plugin_languages: yes
                  plugin_languages_analysis_timeout: 15
                  plugin_languages_analysis_timeout_repositories: 7.5
                  plugin_languages_categories: markup, programming
                  plugin_languages_colors: github
                  plugin_languages_limit: 8
                  plugin_languages_recent_categories: markup, programming
                  plugin_languages_recent_days: 14
                  plugin_languages_recent_load: 300
                  plugin_languages_sections: most-used
                  plugin_languages_threshold: 0%

            - name: Adjust output
              run: |
                  cp /metrics_renders/* ./
                  sed -i 's/[0-9]*\s*members/No public members/g' github-metrics.svg

            - name: Commit to the repo
              run: |
                  git config --global user.name "Github Action"
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"
                  git add .
                  git commit -m 'Update metrics' || true
                  git push
